--- 
spring: 
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    password: root123
    url: "jdbc:mysql://mysql-service.nl-amis-testing/test?allowPublicKeyRetrieval=true&useSSL=false"
    username: root
  jpa: 
    hibernate: 
      ddl-auto: create
      show-sql: true
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5Dialect
        use-new-id-generator-mappings: false
